//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinTachiePlugin.LayerValueListController {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinTachiePlugin.LayerValueListController.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   差分制御 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupeName_LayerValue {
            get {
                return ResourceManager.GetString("GroupeName_LayerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セラールとアブリールの値の使い方を指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamDesc_AnimationMode {
            get {
                return ResourceManager.GetString("ParamDesc_AnimationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0%~100%の範囲外になったときの値の変換方法を指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamDesc_OuterMode {
            get {
                return ResourceManager.GetString("ParamDesc_OuterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アブリール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Abrir {
            get {
                return ResourceManager.GetString("ParamName_Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_AnimationMode {
            get {
                return ResourceManager.GetString("ParamName_AnimationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セラール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Cerrar {
            get {
                return ResourceManager.GetString("ParamName_Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Comment {
            get {
                return ResourceManager.GetString("ParamName_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   範囲外の値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_OuterMode {
            get {
                return ResourceManager.GetString("ParamName_OuterMode", resourceCulture);
            }
        }
    }
}
