//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinTachiePlugin.Parts {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinTachiePlugin.Parts.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   複製元とは別のタグを持たせますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DuplicateWarning {
            get {
                return ResourceManager.GetString("DuplicateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jsonデータ内に変換できないエフェクトを検知しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorLog_DeserializeVideoEffects {
            get {
                return ResourceManager.GetString("ErrorLog_DeserializeVideoEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロック情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupeName_BlockInfo {
            get {
                return ResourceManager.GetString("GroupeName_BlockInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中心位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupeName_CenterPoint {
            get {
                return ResourceManager.GetString("GroupeName_CenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupeName_Drawing {
            get {
                return ResourceManager.GetString("GroupeName_Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーツ個別エフェクト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupeName_PartEffect {
            get {
                return ResourceManager.GetString("GroupeName_PartEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブ拡大率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupeName_SubScale {
            get {
                return ResourceManager.GetString("GroupeName_SubScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値の依存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupeName_ValueDependent {
            get {
                return ResourceManager.GetString("GroupeName_ValueDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親のエフェクトによるカメラ移動を有効にします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamDesc_CameraDependent {
            get {
                return ResourceManager.GetString("ParamDesc_CameraDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親のエフェクトによる非遅延エフェクトを有効にします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamDesc_UnlazyEffectDependent {
            get {
                return ResourceManager.GetString("ParamDesc_UnlazyEffectDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_BusNum {
            get {
                return ResourceManager.GetString("ParamName_BusNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カメラ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Camera {
            get {
                return ResourceManager.GetString("ParamName_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Comment {
            get {
                return ResourceManager.GetString("ParamName_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合成モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Composition {
            get {
                return ResourceManager.GetString("ParamName_Composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   横方向 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Exp_X {
            get {
                return ResourceManager.GetString("ParamName_Exp_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   縦方向 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Exp_Y {
            get {
                return ResourceManager.GetString("ParamName_Exp_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_ImagePath {
            get {
                return ResourceManager.GetString("ParamName_ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置を保持 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_KeepPlace {
            get {
                return ResourceManager.GetString("ParamName_KeepPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   差分レイヤー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_LayerValues {
            get {
                return ResourceManager.GetString("ParamName_LayerValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左右反転 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Mirror {
            get {
                return ResourceManager.GetString("ParamName_Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不透明度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Opacity {
            get {
                return ResourceManager.GetString("ParamName_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Parent {
            get {
                return ResourceManager.GetString("ParamName_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転角 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Rotate {
            get {
                return ResourceManager.GetString("ParamName_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Scale {
            get {
                return ResourceManager.GetString("ParamName_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_TagName {
            get {
                return ResourceManager.GetString("ParamName_TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非遅延エフェクト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_UnlazyEffectDependent {
            get {
                return ResourceManager.GetString("ParamName_UnlazyEffectDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_X {
            get {
                return ResourceManager.GetString("ParamName_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X/Y/Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_XYZ {
            get {
                return ResourceManager.GetString("ParamName_XYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Y {
            get {
                return ResourceManager.GetString("ParamName_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Z {
            get {
                return ResourceManager.GetString("ParamName_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z順描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_ZOrder {
            get {
                return ResourceManager.GetString("ParamName_ZOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じタグを持つパーツが存在します。
        ///パーツに別のタグを持たせますか？
        ///タグ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SameTagWarning {
            get {
                return ResourceManager.GetString("SameTagWarning", resourceCulture);
            }
        }
    }
}
