//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinTachiePlugin.LayerValueListController.Controller {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinTachiePlugin.LayerValueListController.Controller.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   セラール（の最初の）値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AbrirValueToolTip {
            get {
                return ResourceManager.GetString("AbrirValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイヤー軸を一つ追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddButtonToolTip {
            get {
                return ResourceManager.GetString("AddButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アブリール（の最初の）値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CerrarValueToolTip {
            get {
                return ResourceManager.GetString("CerrarValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されているレイヤー軸を一つ下と入れ替える に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveDownButtonToolTip {
            get {
                return ResourceManager.GetString("MoveDownButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されているレイヤー軸を一つ上と入れ替える に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveUpButtonToolTip {
            get {
                return ResourceManager.GetString("MoveUpButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されているレイヤー軸を削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveButtonToolTip {
            get {
                return ResourceManager.GetString("RemoveButtonToolTip", resourceCulture);
            }
        }
    }
}
