//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinTachiePlugin.Parts.Controller {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinTachiePlugin.Parts.Controller.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   【表示／非表示】
        ///描画するか否かを切り替えられます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppearCheckBoxToolTip {
            get {
                return ResourceManager.GetString("AppearCheckBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusPanelText {
            get {
                return ResourceManager.GetString("BusPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【バス】
        ///パーツの描画優先度。
        ///数字が高い方が後の方で描画され、画像上では手前に映ります。
        ///（表示される数値は、アイテム上で最初のフレームにおける数値です。） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusPanelToolTip {
            get {
                return ResourceManager.GetString("BusPanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommentPanelText {
            get {
                return ResourceManager.GetString("CommentPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【備考】
        ///メモか何か書くと良いでしょう。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommentPanelToolTip {
            get {
                return ResourceManager.GetString("CommentPanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全ブロックにチェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuCheckAllHeader {
            get {
                return ResourceManager.GetString("ContextMenuCheckAllHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【全ブロックにチェック】
        ///描画順序リスト内の全パーツブロックに
        ///チェックを入れます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuCheckAllToolTip {
            get {
                return ResourceManager.GetString("ContextMenuCheckAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択中のブロックにのみチェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuCheckOnlyOneHeader {
            get {
                return ResourceManager.GetString("ContextMenuCheckOnlyOneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【全ブロックにチェック】
        ///選択されているパーツブロックだけに
        ///チェックを入れた状態にします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuCheckOnlyOneToolTip {
            get {
                return ResourceManager.GetString("ContextMenuCheckOnlyOneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuCopyHeader {
            get {
                return ResourceManager.GetString("ContextMenuCopyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【コピー】
        ///選択されているパーツをコピーします。
        ///コピーされたパーツは『貼り付け』で新たなパーツとして挿入できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuCopyToolTip {
            get {
                return ResourceManager.GetString("ContextMenuCopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuCutHeader {
            get {
                return ResourceManager.GetString("ContextMenuCutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【切り取り】
        ///選択されているパーツを取り除きます。
        ///切り取られたパーツは『貼り付け』で再挿入できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuCutToolTip {
            get {
                return ResourceManager.GetString("ContextMenuCutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複製 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuDuplicationHeader {
            get {
                return ResourceManager.GetString("ContextMenuDuplicationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【複製】
        ///選択されているパーツをひとつ下に複製します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuDuplicationToolTip {
            get {
                return ResourceManager.GetString("ContextMenuDuplicationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuPasteHeader {
            get {
                return ResourceManager.GetString("ContextMenuPasteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【貼り付け】
        ///『切り取り』または『コピー』されたパーツを新たなパーツとして挿入できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuPasteToolTip {
            get {
                return ResourceManager.GetString("ContextMenuPasteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuRemoveHeader {
            get {
                return ResourceManager.GetString("ContextMenuRemoveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【削除】
        ///選択されているパーツを削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuRemoveToolTip {
            get {
                return ResourceManager.GetString("ContextMenuRemoveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【パーツデフォルト設定のリロード】
        ///選択されているパーツが指定している画像ファイルに対応するデフォルトパラメータ情報を読み取り、現在の全パラメータを自動編集します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditDefaultButtonReloadToolTip {
            get {
                return ResourceManager.GetString("EditDefaultButtonReloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【パーツデフォルト設定の削除】
        ///選択されているパーツが指定している画像ファイルから、デフォルトのパラメータ情報を取り消します。
        ///(stpiファイル自体は削除されません。) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditDefaultButtonRemoveToolTip {
            get {
                return ResourceManager.GetString("EditDefaultButtonRemoveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【デフォルト設定編集ボタン群】
        ///『パーツブロック』が１つだけ選択されている状態でないと
        ///全ての操作ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditDefaultButtonsToolTip {
            get {
                return ResourceManager.GetString("EditDefaultButtonsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【パーツデフォルト設定の保存／上書き】
        ///選択されているパーツが指定している画像ファイルに、現在のパーツパラメータ情報をデフォルトとして記録します。
        ///(stpiファイルが生成／上書きされます。) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditDefaultButtonWriteToolTip {
            get {
                return ResourceManager.GetString("EditDefaultButtonWriteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【パーツ追加】
        ///パーツツリーから選択されたパーツを追加します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditListButtonAddToolTip {
            get {
                return ResourceManager.GetString("EditListButtonAddToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【ひとつ下に移動】
        ///選択されているパーツを一つ下のパーツと入れ替えます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditListButtonMoveDownToolTip {
            get {
                return ResourceManager.GetString("EditListButtonMoveDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【ひとつ上に移動】
        ///選択されているパーツを一つ上のパーツと入れ替えます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditListButtonMoveUpToolTip {
            get {
                return ResourceManager.GetString("EditListButtonMoveUpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【パーツ削除】
        ///選択されているパーツを取り除きます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditListButtonRemoveToolTip {
            get {
                return ResourceManager.GetString("EditListButtonRemoveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【リスト編集ボタン群】
        ///『パーツブロック』の選択状態によっては一部の操作ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditListButtonsToolTip {
            get {
                return ResourceManager.GetString("EditListButtonsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【リストの高さ】
        ///描画順序リストの高さを調整できます。
        ///プラグイン内でこの値は共有されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HeightOfListSliderToolTip {
            get {
                return ResourceManager.GetString("HeightOfListSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParentPanelText {
            get {
                return ResourceManager.GetString("ParentPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【親】
        ///タグ名が一致するパーツと動きを連動します。
        ///Blenderでいう親ボーンに相当します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParentPanelToolTip {
            get {
                return ResourceManager.GetString("ParentPanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【パーツブロック】
        ///パーツたちの内のひとつを表しています。
        ///右クリックで特殊操作ができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartBlockToolTip {
            get {
                return ResourceManager.GetString("PartBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画順序 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartListControllerText {
            get {
                return ResourceManager.GetString("PartListControllerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【描画順序リスト】
        ///新しくパーツを追加するときは
        ///右側の「＋」を押してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartListToolTip {
            get {
                return ResourceManager.GetString("PartListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【STPバージョン】
        ///本プラグインのバージョンです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STPVersionToolTip {
            get {
                return ResourceManager.GetString("STPVersionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TagPanelText {
            get {
                return ResourceManager.GetString("TagPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【タグ】
        ///パーツの名前です。
        ///他のパーツの親にしたいときは名前を付けましょう。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TagPanelToolTip {
            get {
                return ResourceManager.GetString("TagPanelToolTip", resourceCulture);
            }
        }
    }
}
