//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinTachiePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinTachiePlugin.Properties.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アニメーションのリンク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_GroupName {
            get {
                return ResourceManager.GetString("PartAnimationLink_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode_Add {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   乗算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode_Multiply {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode_Override {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ｱﾆﾒｰｼｮﾝタグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_Tag {
            get {
                return ResourceManager.GetString("PartAnimationLink_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンク先のパーツ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_TargetPart {
            get {
                return ResourceManager.GetString("PartAnimationLink_TargetPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode_Limit {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode_Loop {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   往復 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode_Shuttle {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode_Shuttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_A {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Amplitude {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Amplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_B {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Close {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_GroupName {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切片 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Intercept {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Intercept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   間隔 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Interval {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Open {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Output {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セリフないとき に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Silent {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Start {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位相 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Theta {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Theta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遷移 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Transition {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定期ループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_PeriodicLoop {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_PeriodicLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定期往復 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_PeriodicShuttle {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_PeriodicShuttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A × B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Product {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シンプル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Simple {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Sin {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A + B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Sum {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   口パク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_VoiceVolume {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_VoiceVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   口パク＋ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_VoiceVolumePlus {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_VoiceVolumePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueUnit_Second {
            get {
                return ResourceManager.GetString("ValueUnit_Second", resourceCulture);
            }
        }
    }
}
