//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinTachiePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinTachiePlugin.Properties.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AskNameOfNewTemplateDialog_AskOverwriteTemplate {
            get {
                return ResourceManager.GetString("AskNameOfNewTemplateDialog_AskOverwriteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンプレートの名前を入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AskNameOfNewTemplateDialog_TemplateName {
            get {
                return ResourceManager.GetString("AskNameOfNewTemplateDialog_TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンプレート名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AskNameOfNewTemplateDialog_Title {
            get {
                return ResourceManager.GetString("AskNameOfNewTemplateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムポイントを指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterPointMode_CustomPointName {
            get {
                return ResourceManager.GetString("CenterPointMode_CustomPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書きしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterPointMode_DontOverride {
            get {
                return ResourceManager.GetString("CenterPointMode_DontOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定しない（画像の中心） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterPointMode_DontSet {
            get {
                return ResourceManager.GetString("CenterPointMode_DontSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   座標を指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CenterPointMode_OnlyCoordinate {
            get {
                return ResourceManager.GetString("CenterPointMode_OnlyCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親パーツにクリッピング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClippingMode_ClipToParent {
            get {
                return ResourceManager.GetString("ClippingMode_ClipToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリッピング先のパーツを指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClippingMode_ClipWithTag {
            get {
                return ResourceManager.GetString("ClippingMode_ClipWithTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリッピングしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClippingMode_DontClip {
            get {
                return ResourceManager.GetString("ClippingMode_DontClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuItemHeader_Common_Copy {
            get {
                return ResourceManager.GetString("ContextMenuItemHeader_Common_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuItemHeader_Common_Cut {
            get {
                return ResourceManager.GetString("ContextMenuItemHeader_Common_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複製 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuItemHeader_Common_Duplicate {
            get {
                return ResourceManager.GetString("ContextMenuItemHeader_Common_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuItemHeader_Common_Paste {
            get {
                return ResourceManager.GetString("ContextMenuItemHeader_Common_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustomNamePoint_DefaultName {
            get {
                return ResourceManager.GetString("CustomNamePoint_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムポイントを作る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustomPointDefineMode_DoMake {
            get {
                return ResourceManager.GetString("CustomPointDefineMode_DoMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムポイントを作らない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustomPointDefineMode_DontMake {
            get {
                return ResourceManager.GetString("CustomPointDefineMode_DontMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点の名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustomPointParam_Name {
            get {
                return ResourceManager.GetString("CustomPointParam_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   stpiファイルから情報を取得できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_FailToGetInfoFromStpi {
            get {
                return ResourceManager.GetString("ErrorMessage_FailToGetInfoFromStpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   stpsiファイルから情報を取得できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_FailToGetInfoFromStpsi {
            get {
                return ResourceManager.GetString("ErrorMessage_FailToGetInfoFromStpsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   stpiファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_FailToReadStpi {
            get {
                return ResourceManager.GetString("ErrorMessage_FailToReadStpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   stpsiファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_FailToReadStpsi {
            get {
                return ResourceManager.GetString("ErrorMessage_FailToReadStpsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   stpsiファイルの出力時にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_FailToSerializeStpsi {
            get {
                return ResourceManager.GetString("ErrorMessage_FailToSerializeStpsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpensionMessage_InputIsNull {
            get {
                return ResourceManager.GetString("ExpensionMessage_InputIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中心位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_CenterPoint {
            get {
                return ResourceManager.GetString("GroupName_CenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムポイント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_CustomPoint {
            get {
                return ResourceManager.GetString("GroupName_CustomPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_Drawing {
            get {
                return ResourceManager.GetString("GroupName_Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_IK {
            get {
                return ResourceManager.GetString("GroupName_IK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイヤー情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_LayerInfo {
            get {
                return ResourceManager.GetString("GroupName_LayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画原点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_Origin {
            get {
                return ResourceManager.GetString("GroupName_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーツ個別エフェクト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_PartEffect {
            get {
                return ResourceManager.GetString("GroupName_PartEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値の依存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_ValueDependent {
            get {
                return ResourceManager.GetString("GroupName_ValueDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書きしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IKMode_DontOverride {
            get {
                return ResourceManager.GetString("IKMode_DontOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IKを使用しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IKMode_None {
            get {
                return ResourceManager.GetString("IKMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IKを使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IKMode_TypeA {
            get {
                return ResourceManager.GetString("IKMode_TypeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効な差分指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageFileNode_Error_InvalidValue {
            get {
                return ResourceManager.GetString("ImageFileNode_Error_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インデックスが正しく指定されていないリーフをImageFileNodeManagerに足そうとしました。ごめんなさい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageFileNodeManager_Error_InvalidIndex {
            get {
                return ResourceManager.GetString("ImageFileNodeManager_Error_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InverseKinematics_EndEffectorPartTag {
            get {
                return ResourceManager.GetString("InverseKinematics_EndEffectorPartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続先ﾎﾟｲﾝﾄ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InverseKinematics_EndEffectorPointName {
            get {
                return ResourceManager.GetString("InverseKinematics_EndEffectorPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続先X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InverseKinematics_EndEffectorPointX {
            get {
                return ResourceManager.GetString("InverseKinematics_EndEffectorPointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続先Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InverseKinematics_EndEffectorPointY {
            get {
                return ResourceManager.GetString("InverseKinematics_EndEffectorPointY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IKモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InverseKinematics_IkMode {
            get {
                return ResourceManager.GetString("InverseKinematics_IkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中間関節 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InverseKinematics_JointPartTag {
            get {
                return ResourceManager.GetString("InverseKinematics_JointPartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続元ﾎﾟｲﾝﾄ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InverseKinematics_PreEndEffectorPointName {
            get {
                return ResourceManager.GetString("InverseKinematics_PreEndEffectorPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続元X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InverseKinematics_PreEndEffectorPointX {
            get {
                return ResourceManager.GetString("InverseKinematics_PreEndEffectorPointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続元Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InverseKinematics_PreEndEffectorPointY {
            get {
                return ResourceManager.GetString("InverseKinematics_PreEndEffectorPointY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InverseKinematics_RootPartTag {
            get {
                return ResourceManager.GetString("InverseKinematics_RootPartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayerType_Group {
            get {
                return ResourceManager.GetString("LayerType_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayerType_Image {
            get {
                return ResourceManager.GetString("LayerType_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PSD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayerType_Psd {
            get {
                return ResourceManager.GetString("LayerType_Psd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シーン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayerType_Scene {
            get {
                return ResourceManager.GetString("LayerType_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayerType_Video {
            get {
                return ResourceManager.GetString("LayerType_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親の中心 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OriginDefineMode_CenterOfParent {
            get {
                return ResourceManager.GetString("OriginDefineMode_CenterOfParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親の画像の中心 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OriginDefineMode_CenterOfParentSource {
            get {
                return ResourceManager.GetString("OriginDefineMode_CenterOfParentSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親のカスタムポイント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OriginDefineMode_CustomPointOfParent {
            get {
                return ResourceManager.GetString("OriginDefineMode_CustomPointOfParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書きしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OriginDefineMode_DontOverride {
            get {
                return ResourceManager.GetString("OriginDefineMode_DontOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーションのリンク先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_GroupName {
            get {
                return ResourceManager.GetString("PartAnimationLink_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode_Add {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode_DontLink {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode_DontLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書きしない（デフォルト：「リンクしない」） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode_DontOverride {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode_DontOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   乗算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode_Multiply {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ｱﾆﾒｰｼｮﾝタグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_TargetAnimationTag {
            get {
                return ResourceManager.GetString("PartAnimationLink_TargetAnimationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーツタグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_TargetPartTag {
            get {
                return ResourceManager.GetString("PartAnimationLink_TargetPartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書きしない（デフォルト：「制限」） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode_DontOverride {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode_DontOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode_Limit {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode_Loop {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   往復 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode_Shuttle {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode_Shuttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_A {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Amplitude {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Amplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ｱﾆﾒｰｼｮﾝタグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_AnimationTag {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_AnimationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_B {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Close {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Comment {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_GroupName {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Index {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切片 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Intercept {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Intercept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   間隔 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Interval {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   間隔A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_IntervalA {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_IntervalA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   間隔B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_IntervalB {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_IntervalB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Offset {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Open {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Output {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_PlaybackSpeed {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_PlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セリフないとき に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Silent {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生開始位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_StartFrameNumber {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_StartFrameNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_StringInput {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_StringInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位相 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Theta {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Theta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遷移 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Transition {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あいうえお口パク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_AIUEOMouth {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_AIUEOMouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_AudioFile {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_AudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定期ループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_PeriodicLoop {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_PeriodicLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定期往復 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_PeriodicShuttle {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_PeriodicShuttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A × B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Product {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランダムループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_RandomLoop {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_RandomLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランダム往復 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_RandomShuttle {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_RandomShuttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シンプル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Simple {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Sin {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_StringInput {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_StringInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A + B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Sum {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量口パク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_VoiceVolume {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_VoiceVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量口パク＋ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_VoiceVolumePlus {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_VoiceVolumePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   多次元でアニメーションを指定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueMode_Multi {
            get {
                return ResourceManager.GetString("PartAnimationValueMode_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーションを指定しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueMode_None {
            get {
                return ResourceManager.GetString("PartAnimationValueMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーションを指定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueMode_Single {
            get {
                return ResourceManager.GetString("PartAnimationValueMode_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueVeiwer_A {
            get {
                return ResourceManager.GetString("PartAnimationValueVeiwer_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーションタグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueVeiwer_AnimationTag {
            get {
                return ResourceManager.GetString("PartAnimationValueVeiwer_AnimationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueVeiwer_AnmOpeMode {
            get {
                return ResourceManager.GetString("PartAnimationValueVeiwer_AnmOpeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueVeiwer_B {
            get {
                return ResourceManager.GetString("PartAnimationValueVeiwer_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueVeiwer_Close {
            get {
                return ResourceManager.GetString("PartAnimationValueVeiwer_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueVeiwer_Comment {
            get {
                return ResourceManager.GetString("PartAnimationValueVeiwer_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueVeiwer_Index {
            get {
                return ResourceManager.GetString("PartAnimationValueVeiwer_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueVeiwer_Open {
            get {
                return ResourceManager.GetString("PartAnimationValueVeiwer_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   黙 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationValueVeiwer_Silent {
            get {
                return ResourceManager.GetString("PartAnimationValueVeiwer_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エフェクトを追加する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartEffectOverrideMode_Add {
            get {
                return ResourceManager.GetString("PartEffectOverrideMode_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エフェクトを上書きする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartEffectOverrideMode_Override {
            get {
                return ResourceManager.GetString("PartEffectOverrideMode_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_CenterPoint_CenterMode {
            get {
                return ResourceManager.GetString("PartParam_CenterPoint_CenterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポイント名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_CenterPoint_CustomPointName {
            get {
                return ResourceManager.GetString("PartParam_CenterPoint_CustomPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置を保持 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_CenterPoint_KeepPlace {
            get {
                return ResourceManager.GetString("PartParam_CenterPoint_KeepPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合成モードの変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Blend {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左右反転の合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Inverse {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Inverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値の合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Master {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不透明度の合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Opacity {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   優先度の合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Priority {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転角の合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Rotation {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XYZの合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_XYZ {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_XYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率の合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Zoom {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z順描画の変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_ZSort {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_ZSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合成モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Blend {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左右反転 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Invert {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不透明度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Opacity {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   優先度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Priority {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転角 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Rotation {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_X {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Y {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Z {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Zoom {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   横拡大 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Zoom_X {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Zoom_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   縦拡大 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Zoom_Y {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Zoom_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z順描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_ZSort {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_ZSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_Comment {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_Hide {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   種類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_LayerType {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_LayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリッピングモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_ClippingMode {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_ClippingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイヤー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_EnablePsdLayers {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_EnablePsdLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーツ備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_GroupComment {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_GroupComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_ImageFile {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像を合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_IsCompressFrame {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_IsCompressFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ループ再生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_LoopPlayback {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_LoopPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_Parent {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ｱﾆﾒｰｼｮﾝモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_PartAnimationValueMode {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_PartAnimationValueMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_PartAnimationValues {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_PartAnimationValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーツ備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_PartComment {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_PartComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリッピング先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_PartToClipTo {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_PartToClipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_PlaybackSpeed {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_PlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポイント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_Point {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PSD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_PsdFile {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_PsdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シーン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_SceneId {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_SceneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生開始位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_StartFrameNumber {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_StartFrameNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourceSelectArg_VideoFile {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourceSelectArg_VideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_Tag {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Origin_OriginMode {
            get {
                return ResourceManager.GetString("PartParam_Origin_OriginMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点の名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Origin_PointName {
            get {
                return ResourceManager.GetString("PartParam_Origin_PointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値の依存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_ValueDependent_Mode_Master {
            get {
                return ResourceManager.GetString("PartParam_ValueDependent_Mode_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カメラ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_ValueDependentMode_Camera {
            get {
                return ResourceManager.GetString("PartParam_ValueDependentMode_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左右反転 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_ValueDependentMode_Invert {
            get {
                return ResourceManager.GetString("PartParam_ValueDependentMode_Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不透明度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_ValueDependentMode_Opacity {
            get {
                return ResourceManager.GetString("PartParam_ValueDependentMode_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転角 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_ValueDependentMode_Rotation {
            get {
                return ResourceManager.GetString("PartParam_ValueDependentMode_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非遅延エフェクト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_ValueDependentMode_UnlazyEffect {
            get {
                return ResourceManager.GetString("PartParam_ValueDependentMode_UnlazyEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X/Y/Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_ValueDependentMode_XYZ {
            get {
                return ResourceManager.GetString("PartParam_ValueDependentMode_XYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_ValueDependentMode_Zoom {
            get {
                return ResourceManager.GetString("PartParam_ValueDependentMode_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (デフォルト) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartSourceInfo_DefaultTemplateName {
            get {
                return ResourceManager.GetString("PartSourceInfo_DefaultTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像未指定のパーツブロックを追加しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueListView_AddPartMessage_AskAddEmptyPart {
            get {
                return ResourceManager.GetString("PartValueListView_AddPartMessage_AskAddEmptyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   素材の場所のパスが無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueListView_AddPartMessage_InvalidSourcePath {
            get {
                return ResourceManager.GetString("PartValueListView_AddPartMessage_InvalidSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   素材の場所のパスが無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueListView_AddPartMessage_NotFoundAnyFiles {
            get {
                return ResourceManager.GetString("PartValueListView_AddPartMessage_NotFoundAnyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueListView_ContextMenu_Copy {
            get {
                return ResourceManager.GetString("PartValueListView_ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueListView_ContextMenu_Cut {
            get {
                return ResourceManager.GetString("PartValueListView_ContextMenu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複製 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueListView_ContextMenu_Duplicate {
            get {
                return ResourceManager.GetString("PartValueListView_ContextMenu_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueListView_ContextMenu_Paste {
            get {
                return ResourceManager.GetString("PartValueListView_ContextMenu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全て表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueListView_ContextMenu_ShowAll {
            get {
                return ResourceManager.GetString("PartValueListView_ContextMenu_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択しているパーツのみ表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueListView_ContextMenu_ShowOnlySelected {
            get {
                return ResourceManager.GetString("PartValueListView_ContextMenu_ShowOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueTemplateEditorDialog_Delete {
            get {
                return ResourceManager.GetString("PartValueTemplateEditorDialog_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueTemplateEditorDialog_NewAdd {
            get {
                return ResourceManager.GetString("PartValueTemplateEditorDialog_NewAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueTemplateEditorDialog_Overwrite {
            get {
                return ResourceManager.GetString("PartValueTemplateEditorDialog_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueTemplateEditorDialog_Read {
            get {
                return ResourceManager.GetString("PartValueTemplateEditorDialog_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueTemplateEditorDialog_Rename {
            get {
                return ResourceManager.GetString("PartValueTemplateEditorDialog_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンプレートの編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueTemplateEditorDialog_Title {
            get {
                return ResourceManager.GetString("PartValueTemplateEditorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; のパラメータテンプレート &quot;{1}&quot; を削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueTemplateEditorDialog_Warning_DeleteTemplate {
            get {
                return ResourceManager.GetString("PartValueTemplateEditorDialog_Warning_DeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; のパラメータテンプレート &quot;{1}&quot; に現在のパラメータで上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartValueTemplateEditorDialog_Warning_OverWriteTemplate {
            get {
                return ResourceManager.GetString("PartValueTemplateEditorDialog_Warning_OverWriteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sin型カスタムパーツ立ち絵プラグイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SinTachiePlugin_Title {
            get {
                return ResourceManager.GetString("SinTachiePlugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1.2.0.0 β-0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SinTachiePlugin_Version {
            get {
                return ResourceManager.GetString("SinTachiePlugin_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueDependentMode_Custom {
            get {
                return ResourceManager.GetString("ValueDependentMode_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書きしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueDependentMode_DontOverride {
            get {
                return ResourceManager.GetString("ValueDependentMode_DontOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ✖依存させない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueDependentMode_Off {
            get {
                return ResourceManager.GetString("ValueDependentMode_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ✅依存させる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueDependentMode_On {
            get {
                return ResourceManager.GetString("ValueDependentMode_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   統合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Compose {
            get {
                return ResourceManager.GetString("ValueMode_Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値を混ぜ合わせます。
        ///座標や角度には加算、拡大率や不透明度には乗算を行い、モード系は上書き前のモードが使われます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Compose_Description {
            get {
                return ResourceManager.GetString("ValueMode_Compose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Custom {
            get {
                return ResourceManager.GetString("ValueMode_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータごとに値の合成方法を指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Custom_Description {
            get {
                return ResourceManager.GetString("ValueMode_Custom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書きしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_DontOverride {
            get {
                return ResourceManager.GetString("ValueMode_DontOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Override {
            get {
                return ResourceManager.GetString("ValueMode_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値を上書きします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Override_Description {
            get {
                return ResourceManager.GetString("ValueMode_Override_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueUnit_Second {
            get {
                return ResourceManager.GetString("ValueUnit_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   優先度が等しいときにZ準描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZSortMode_BasedOnPriority {
            get {
                return ResourceManager.GetString("ZSortMode_BasedOnPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書きしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZSortMode_DontOverride {
            get {
                return ResourceManager.GetString("ZSortMode_DontOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   優先度を無視してZ順に描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZSortMode_IgnorePriority {
            get {
                return ResourceManager.GetString("ZSortMode_IgnorePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z座標を無視して優先度順に描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZSortMode_IgnoreZ {
            get {
                return ResourceManager.GetString("ZSortMode_IgnoreZ", resourceCulture);
            }
        }
    }
}
