//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinTachiePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinTachiePlugin.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   親パーツにクリッピング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClippingMode_ClipToParent {
            get {
                return ResourceManager.GetString("ClippingMode_ClipToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリッピング先のパーツを指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClippingMode_ClipWithTag {
            get {
                return ResourceManager.GetString("ClippingMode_ClipWithTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリッピングしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClippingMode_DontClip {
            get {
                return ResourceManager.GetString("ClippingMode_DontClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画原点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_CenterPoint {
            get {
                return ResourceManager.GetString("GroupName_CenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_Drawing {
            get {
                return ResourceManager.GetString("GroupName_Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイヤー情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_LayerInfo {
            get {
                return ResourceManager.GetString("GroupName_LayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayerType_Group {
            get {
                return ResourceManager.GetString("LayerType_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ（画像を合成） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayerType_Group_CompressFrame {
            get {
                return ResourceManager.GetString("LayerType_Group_CompressFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayerType_Image {
            get {
                return ResourceManager.GetString("LayerType_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PSD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayerType_Psd {
            get {
                return ResourceManager.GetString("LayerType_Psd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シーン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayerType_Scene {
            get {
                return ResourceManager.GetString("LayerType_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LayerType_Video {
            get {
                return ResourceManager.GetString("LayerType_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーションのリンク先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_GroupName {
            get {
                return ResourceManager.GetString("PartAnimationLink_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode_Add {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode_DontLink {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode_DontLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   乗算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_LinkOpeMode_Multiply {
            get {
                return ResourceManager.GetString("PartAnimationLink_LinkOpeMode_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ｱﾆﾒｰｼｮﾝタグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_TargetAnimationTag {
            get {
                return ResourceManager.GetString("PartAnimationLink_TargetAnimationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーツタグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationLink_TargetPartTag {
            get {
                return ResourceManager.GetString("PartAnimationLink_TargetPartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode_Limit {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode_Loop {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   往復 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationNormalizationMode_Shuttle {
            get {
                return ResourceManager.GetString("PartAnimationNormalizationMode_Shuttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_A {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Amplitude {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Amplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ｱﾆﾒｰｼｮﾝタグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_AnimationTag {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_AnimationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_B {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Close {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Comment {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_GroupName {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Index {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切片 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Intercept {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Intercept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   間隔 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Interval {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Offset {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Open {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Output {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_PlaybackSpeed {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_PlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セリフないとき に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Silent {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生開始位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_StartFrameNumber {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_StartFrameNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位相 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Theta {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Theta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遷移 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeArg_Transition {
            get {
                return ResourceManager.GetString("PartAnimationOpeArg_Transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_AudioFile {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_AudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定期ループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_PeriodicLoop {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_PeriodicLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定期往復 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_PeriodicShuttle {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_PeriodicShuttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A × B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Product {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A × B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Product1 {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Product1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シンプル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Simple {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Sin {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A + B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_Sum {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   口パク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_VoiceVolume {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_VoiceVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   口パク＋ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartAnimationOpeMode_VoiceVolumePlus {
            get {
                return ResourceManager.GetString("PartAnimationOpeMode_VoiceVolumePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_CenterPoint_CenterMode {
            get {
                return ResourceManager.GetString("PartParam_CenterPoint_CenterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポイント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_CenterPoint_CustomPoint {
            get {
                return ResourceManager.GetString("PartParam_CenterPoint_CustomPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合成モードの変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Blend {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左右反転の合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Inverse {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Inverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値の合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Master {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不透明度の合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Opacity {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転角の合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Rotation {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XYZの合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_XYZ {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_XYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率の合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_Zoom {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z順描画の変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Mode_ZSort {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Mode_ZSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合成モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Blend {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左右反転 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Inverse {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Inverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不透明度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Opacity {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転角 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Rotation {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_X {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Y {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Z {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_Zoom {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z順描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_Drawing_Value_ZSort {
            get {
                return ResourceManager.GetString("PartParam_Drawing_Value_ZSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_Comment {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_Hide {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   種類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_LayerType {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_LayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリッピングモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_ClippingMode {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_ClippingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイヤー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_EnablePsdLayers {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_EnablePsdLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーツ備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_GroupComment {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_GroupComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_ImageFile {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像を合成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_IsCompressFrame {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_IsCompressFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ループ再生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_LoopPlayback {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_LoopPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_Parent {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_PartAnimationValues {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_PartAnimationValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーツ備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_PartComment {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_PartComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリッピング先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_PartToClipTo {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_PartToClipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_PlaybackSpeed {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_PlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポイント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_Point {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PSD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_PsdFile {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_PsdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シーン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_SceneId {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_SceneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生開始位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_StartFrameNumber {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_StartFrameNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_SourseSelectArg_VideoFile {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_SourseSelectArg_VideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartParam_LayerInfo_Tag {
            get {
                return ResourceManager.GetString("PartParam_LayerInfo_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   統合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Compose {
            get {
                return ResourceManager.GetString("ValueMode_Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値を混ぜ合わせます。
        ///座標や角度には加算、拡大率や不透明度には乗算を行い、モード系は上書き前のモードが使われます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Compose_Description {
            get {
                return ResourceManager.GetString("ValueMode_Compose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Custom {
            get {
                return ResourceManager.GetString("ValueMode_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータごとに値の合成方法を指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Custom_Description {
            get {
                return ResourceManager.GetString("ValueMode_Custom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Override {
            get {
                return ResourceManager.GetString("ValueMode_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値を上書きします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueMode_Override_Description {
            get {
                return ResourceManager.GetString("ValueMode_Override_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueUnit_Second {
            get {
                return ResourceManager.GetString("ValueUnit_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループを無視してZ順に描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZSortMode_IgnoreGroup {
            get {
                return ResourceManager.GetString("ZSortMode_IgnoreGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z座標を無視 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZSortMode_IgnoreZ {
            get {
                return ResourceManager.GetString("ZSortMode_IgnoreZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ内でZ順に描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZSortMode_InGroup {
            get {
                return ResourceManager.GetString("ZSortMode_InGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ内でZ順に描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZSortMode_InGroup1 {
            get {
                return ResourceManager.GetString("ZSortMode_InGroup1", resourceCulture);
            }
        }
    }
}
