//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinTachiePlugin.LayerValueListController.Extra.Parameter {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinTachiePlugin.LayerValueListController.Extra.Parameter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Time interval for switching differences (transitions not included) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamDesc_Interval {
            get {
                return ResourceManager.GetString("ParamDesc_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouth opening level when there&apos;s no dialogue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamDesc_NoVoiceValue {
            get {
                return ResourceManager.GetString("ParamDesc_NoVoiceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timing to start moving differences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamDesc_Start {
            get {
                return ResourceManager.GetString("ParamDesc_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time from starting to finish switching differences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamDesc_Transition {
            get {
                return ResourceManager.GetString("ParamDesc_Transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Interval {
            get {
                return ResourceManager.GetString("ParamName_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セリフない時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_NoVoiceValue {
            get {
                return ResourceManager.GetString("ParamName_NoVoiceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Start {
            get {
                return ResourceManager.GetString("ParamName_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamName_Transition {
            get {
                return ResourceManager.GetString("ParamName_Transition", resourceCulture);
            }
        }
    }
}
